---
  version: "3"
  services: 
    php: 
      # image: "becodeorg/php"
      build: "./"
      volumes: 
        - "./src:/var/www/html"
      ports: 
        - "80:80"
    mysql: 
      image: "mariadb"
      restart: "unless-stopped"
      volumes: 
        - "mysql_db:/var/lib/mysql"
      ports: 
        - "3306:3306"
        - "33060:33060"
      environment: 
        MYSQL_ROOT_PASSWORD: "root"
    phpmyadmin: 
      image: "phpmyadmin/phpmyadmin"
      ports: 
        - "8001:80"
      depends_on: 
        - "mysql"
      environment: 
        PMA_HOST: "mysql"
        PMA_USER: "root"
        PMA_PASSWORD: "root"
    mail:
      image: mailhog/mailhog:latest
      restart: always
      ports:
        - 1025:1025
        - 8081:8025
  volumes: 
    mysql_db: 
