-- MySQL Script generated by MySQL Workbench
-- Mon Dec  6 23:26:59 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hikingdb
-- -----------------------------------------------------
-- Data base for the hiking php project
DROP SCHEMA IF EXISTS `hikingdb` ;

-- -----------------------------------------------------
-- Schema hikingdb
--
-- Data base for the hiking php project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hikingdb` ;
USE `hikingdb` ;

-- -----------------------------------------------------
-- Table `hikingdb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hikingdb`.`users` ;

CREATE TABLE IF NOT EXISTS `hikingdb`.`users` (
  `userNickname` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `category` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`userNickname`),
  UNIQUE INDEX `nickName_UNIQUE` (`userNickname` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hikingdb`.`hikes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hikingdb`.`hikes` ;

CREATE TABLE IF NOT EXISTS `hikingdb`.`hikes` (
  `idhike` INT NOT NULL AUTO_INCREMENT,
  `hikeName` VARCHAR(45) NULL,
  `dificulty` VARCHAR(10) NULL,
  `distance` FLOAT NULL,
  `duration` TIME NULL,
  `elevationGain` FLOAT NULL,
  `creatDate` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,
  `modifDate` TIMESTAMP  DEFAULT NOW() ON UPDATE NOW(),
  `userNickname` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idhike`),
  UNIQUE INDEX `idhike_UNIQUE` (`idhike` ASC) VISIBLE,
  INDEX `userNickName_idx` (`userNickname` ASC) VISIBLE,
  CONSTRAINT `userNickname`
    FOREIGN KEY (`userNickname`)
    REFERENCES `hikingdb`.`users` (`userNickname`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO users (userNickname,email,password,category) VALUES ('admin','admin@gmail.com','admin','admin');
INSERT INTO users (userNickname,email,password,category) VALUES ('user1','user1@gmail.com','0000','user');

INSERT INTO hikes (hikeName,dificulty,distance,duration,elevationGain,userNickname)
VALUES ('Madura mountains','Medium',4.2,'8:30:00',4,'admin');
INSERT INTO hikes (hikeName,dificulty,distance,duration,elevationGain,userNickname)
VALUES ('Bella forest','Easy',1.5,'8:30:00',2,'user1');